# Generated by Django 5.0.2 on 2024-03-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_bode_review_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-vote_ratio', '-vote_total', '-created']},
        ),
    ]
